batch_size: 2
eval_fs_args:
  batch_size: 2
  ep_per_batch: 1
  n_query: 1
  n_shot: 1
  n_way: 2
eval_fs_epoch: 5
fs_dataset: village-clss
fs_dataset_args:
  root_path: F:\Dataset\tradition_villages_old\Classification
  split: val
max_epoch: 75
model: classifier
model_args:
  classifier: linear-classifier
  classifier_args:
    n_classes: 6
  encoder: resnet12
  encoder_args: {}
num_workers: 0
optimizer: adam
optimizer_args:
  lr: 0.001
  milestones:
  - 50
  weight_decay: 0.0005
train_dataset: village-clss
train_dataset_args:
  root_path: F:\Dataset\tradition_villages_old\Classification
  split: train
val_dataset: village-clss
val_dataset_args:
  root_path: F:\Dataset\tradition_villages_old\Classification
  split: val
