val_dataset: village-segm
val_dataset_args: {root_path: F:\Dataset\tradition_villages_old\Segmentation}

model: mtss
model_args:
    encoder: resnet50
    encoder_args: {output_stride: 16, pretrained: True} # choices=[8, 16]
    classifier_args: { n_classes: 7 }

load: ./save/village_segm-mtss_resnet50/epoch-last.pth
separable_conv: False
batch_size: 2