train_dataset: village-segm
train_dataset_args: {root_path: F:\Dataset\villages_old dataset\Segmentation, split: train}
val_dataset: village-segm
val_dataset_args: {root_path: F:\Dataset\villages_old dataset\Segmentation, split: val}

model: mtss
model_args:
    encoder: resnet50
    encoder_args: {output_stride: 16, pretrained: True} # choices=[8, 16]
    classifier_args: { n_classes: 7 }

batch_size: 2
max_epoch: 75
optimizer: adam
optimizer_args: {lr: 1.e-3, weight_decay: 5.e-4, milestones:[50]}

separable_conv: False
