train_dataset: village-clss-mul
train_dataset_args: {root_path: F:\Dataset\tradition_villages_old\Classification, split: train}
val_dataset: village-clss-mul
val_dataset_args: {root_path: F:\Dataset\tradition_villages_old\Classification, split: val}
fs_dataset: village-clss-mul
fs_dataset_args: {root_path: F:\Dataset\tradition_villages_old\Classification, split: val}
eval_fs_args:
    n_way: 2
    n_query: 1
    n_shot: 1
    ep_per_batch: 1
    batch_size: 2

model: classifier
model_args:
    encoder: resnet12-mul
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: { n_classes: 6 }

batch_size: 2
eval_fs_epoch: 1
max_epoch: 75
optimizer: adam
optimizer_args: {lr: 1.e-3, weight_decay: 5.e-4, milestones:[50]}

num_workers: 0