train_dataset: villageEP-clss
train_dataset_args: {root_path: F:\Dataset\traditional villages\villageEP_GZ\Classification, split: train, augment: flip}
val_dataset: villageEP-clss
val_dataset_args: {root_path: F:\Dataset\traditional villages\villageEP_GZ\Classification, split: val}
fs_dataset: villageEP-clss
fs_dataset_args: {root_path: F:\Dataset\traditional villages\villageEP_GZ\Classification, split: val}
eval_fs_args:
    n_way: 3
    n_query: 5
    n_shot: 1
    ep_per_batch: 2
    train_batches: 20

model: classifier
model_args:
    encoder: resnet12-a
    encoder_args: {input_channels: 1}
    classifier: linear-classifier
    classifier_args: { n_classes: 6 }

batch_size: 16
eval_fs_epoch: 5
max_epoch: 75
optimizer: adam
optimizer_args: {lr: 1.e-3, weight_decay: 5.e-4, milestone: [40, 60]}

num_workers: 0