train_dataset: road-segm
train_dataset_args: {root_path: F:\Dataset\road dataset, split: train}
val_dataset: road-segm
val_dataset_args: {root_path: F:\Dataset\road dataset, split: val}

model: d-unet

batch_size: 2
max_epoch: 75
optimizer: adam
optimizer_args: {lr: 1.e-3, weight_decay: 5.e-4, milestone: [50]}

